name: spigotexample
version: '${version}'
main: net.main.SpigotExample
api-version: '1.20'

# Replace "kit" with the name of your command.
commands:
  kit:
    description: Your description
    usage: /<command>
  helloblock:
    description: Places a snowy grass block at x,y,z and greets the world
    usage: /helloblock x y z
  remove:
    description: Places an air block at x,y,z and says that they destroy something
    usage: /remove x y z
  load:
    description: Loads a savestate
    usage: /load commitname