name: gitcraft
version: '${project.version}'
main: top.gitcraft.GitCraft
api-version: '1.20'
depend: [ CoreProtect ]
# Replace "kit" with the name of your command.
commands:
  gcload:
    description: Loads a savestate
    usage: /gcload saveName
  gcsave:
    description: saves a timestamp with a name
    usage: /gcsave saveName
  gcDeleteSave:
    description: deletes a timestamp with a name
    usage: /gcDeleteSave saveName

  #merge commands
  automerge:
    description: Automatically merge everything that the player changed into the original world
    usage: /automerge <schematicName>
  areamerge:
    description: Automatically merge a player selected area into the original world
    usage: /areamerge <schematicName>

  #schematic commands
  generateschematic:
    description: Automatically generate schematic from all player made changes or player selected area
    usage: /generateschematic [area | all] <schematicName>
  pasteschematic:
    description: Automatically paste schematic into the original world
    usage: /pasteschematic [area | all] <schematicName>

  #menu commands
  gcmenu:
    description: Shows the GitCraft menu
    usage: /gcmenu
  gcworldmenu:
    description: Shows the world menu
    usage: /gcworldmenu

  #world-lists - Join, Create, Delete
  gclist:
    description: List worldes
    usage: /gclist [join|create|delete]

  #commands - Join, Create, Delete
  gcjoin:
    description: Join world
    usage: /gcjoin <name>
  gccreate:
    description: Create a world
    usage: /gccreate <name>
  gcdelete:
    description: Delete a world
    usage: /gcdelete <name>
  gcWETest:
    description: copy an area in front of the player and pastes it  5 xdiff
    usage: /gcWETest

  #commands - Set positions for area select
  gcSetPos1:
    description: Set position 1 below the player
    usage: /gcSetPos1
  gcSetPos2:
    description: Set position 2 below the player
    usage: /gcSetPos2
  gcGetSelection:
    description: Get the selection
    usage: /gcGetSelection
