name: gitcraft
version: '${project.version}'
main: top.gitcraft.GitCraft
api-version: '1.20'
depend: [ CoreProtect ]

commands:
  gc:
    description: GitCraft main command
    usage: /gc [main|world|load|create|merge|delete] [<args>]

  gcload:
    description: Loads a savestate
    usage: /gcload saveName
  gcsave:
    description: saves a timestamp with a name
    usage: /gcsave saveName
  gcdeletesave:
    description: deletes a timestamp with a name
    usage: /gcdeletesave saveName

  #merge commands
  automerge:
    description: Automatically merge everything that the player changed into the original world
    usage: /autoMerge  <fromWorldName> <targetWorldName> <mergeWorldName>
  areamerge:
    description: Creates a schematic from clipboard and pastes clipboard content into the target world and deletes the current world
    usage: /areamerge <targetWorld>
  gcdiscardmerge:
    description: Teleports player back into his previous world and deletes merge world
    usage: /gcdiscardmerge <previousWorld>
  gccreatemergeworld:
    description: Manually creates a void world
    usage: /gccreatemergeworld
  merge:
    description: Test merge a player selected area into the original world
    usage: /merge <fromWorldName> <targetWorldName> <mergeWorldName>
  gcmergemenu:
    description: Open the merge menu
    usage: /gcmergemenu

  #schematic commands
  generateschematic:
    description: Automatically generate schematic from all player made changes or player selected area
    usage: /generateschematic [area | all] <schematicName>
  generateschematicfromarea:
    description: Automatically generate schematic from all player changed blocks in a pre-selected area
    usage: /generateschematicfromarea <schematicName>
  pasteschematic:
    description: Automatically paste schematic into the original world
    usage: /pasteschematic [area | all] <schematicName>
  gcshowschem:
    description: Prints player based or entire Schematic History if no player name is provided
    usage: /gcshowschem <PlayerName>

  #menu commands
  gcmenu:
    description: Shows the GitCraft menu
    usage: /gcmenu
  gcworldmenu:
    description: Shows the world menu
    usage: /gcworldmenu
  gcsavemenu:
    description: Shows the save menu
    usage: /gcsavemenu
  gcschematicmenu:
    description: Shows the schematic menu
    usage: /gcschematicmenu

  #commands - Join, Create, Delete
  gcjoin:
    description: Join world
    usage: /gcjoin <name>
  gccreate:
    description: Create a world
    usage: /gccreate <name>
  gcdelete:
    description: Delete a world
    usage: /gcdelete <name>

  #commands - Set positions for area select
  gcSetPos1:
    description: Set position 1 below the player
    usage: /gcSetPos1
  gcSetPos2:
    description: Set position 2 below the player
    usage: /gcSetPos2
  gcGetSelection:
    description: Get the selection
    usage: /gcGetSelection
  gcDeselectArea:
    description: Deselects the player's selection
    usage: /gcdeselectarea
