name: spigotexample
version: '${version}'
main: net.main.SpigotExample
api-version: '1.20'

# Replace "kit" with the name of your command.
commands:
  kit:
    description: Your description
    usage: /<command>