# SPDX-FileCopyrightText: 2024 TOP Team 8 GitCraft
#
# SPDX-License-Identifier: EUPL-1.2
# SPDX-License-Identifier: GPL-3.0-or-later

name: spigotexample
version: '${version}'
main: net.main.SpigotExample
api-version: '1.20'

# Replace "kit" with the name of your command.
commands:
  kit:
    description: Your description
    usage: /<command>